version: "2"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  
  mybwf:
    image: "mybwf:latest"
    restart: always
    volumes:
      - ./src:/root/src
